// Generated by Portfolio Studio. Edit content/*.json, not this file.
export const ORIGIN = "https://wik-wav.github.io";
export type RouteMeta = { titlePL: string; titleEN: string; descriptionPL: string; descriptionEN: string; image?: string; imageAltPL?: string; imageAltEN?: string; year?: string; };
export const routeMetadata: Record<string, RouteMeta> = {
  "/": {
    "titlePL": "Wiktor Sielaszuk — profil",
    "titleEN": "Wiktor Sielaszuk — profile",
    "descriptionPL": "Profil Wiktora Sielaszuka: projektowanie, sztuka, systemy wizualne i badania.",
    "descriptionEN": "Wiktor Sielaszuk’s profile: design, art, visual systems, and research."
  },
  "/portfolio/": {
    "titlePL": "Portfolio — Wiktor Sielaszuk",
    "titleEN": "Portfolio — Wiktor Sielaszuk",
    "descriptionPL": "Wszystkie publiczne prace Wiktora Sielaszuka z filtrowaniem według projektu, roku, medium i typu.",
    "descriptionEN": "All public work by Wiktor Sielaszuk, filterable by project, year, medium, and type."
  },
  "/projects/": {
    "titlePL": "Projekty — Wiktor Sielaszuk",
    "titleEN": "Projects — Wiktor Sielaszuk",
    "descriptionPL": "Wybrane projekty Wiktora Sielaszuka z opisami założeń, procesu, roli i mediów.",
    "descriptionEN": "Selected projects by Wiktor Sielaszuk with context on concept, process, role, and media."
  },
  "/projects/latentne/": {
    "titlePL": "Latentne — Wiktor Sielaszuk",
    "titleEN": "Latentne — Wiktor Sielaszuk",
    "descriptionPL": "Magisterska praca artystyczna: cykl 12 cyfrowych wydruków badających rolę ludzkiej intencji i sprawczości w sztuce generatywnej.",
    "descriptionEN": "Master’s artistic work: a series of 12 digital prints examining human intention and agency in generative art.",
    "image": "assets/media/degree/latentne-01-graph-of-babel.webp",
    "imageAltPL": "Magisterska praca artystyczna: cykl 12 cyfrowych wydruków badających rolę ludzkiej intencji i sprawczości w sztuce generatywnej.",
    "imageAltEN": "Master’s artistic work: a series of 12 digital prints examining human intention and agency in generative art.",
    "year": "2026"
  },
  "/projects/para-analog-on/": {
    "titlePL": "Para-analog-on — Wiktor Sielaszuk",
    "titleEN": "Para-analog-on — Wiktor Sielaszuk",
    "descriptionPL": "Aneks dyplomowy: otwarty protokół przekształcający opis obrazu od tysiąca słów do dwóch kluczowych wyrazów.",
    "descriptionEN": "Diploma annex: an open protocol transforming an image description from one thousand words into two key terms.",
    "image": "assets/media/degree/para-analog-on-01-w.webp",
    "imageAltPL": "Aneks dyplomowy: otwarty protokół przekształcający opis obrazu od tysiąca słów do dwóch kluczowych wyrazów.",
    "imageAltEN": "Diploma annex: an open protocol transforming an image description from one thousand words into two key terms.",
    "year": "2026"
  },
  "/projects/gaijin-no-mittsu-no-kuusou/": {
    "titlePL": "外人の三つの空想 / A Gaijin’s Three Visions — Wiktor Sielaszuk",
    "titleEN": "外人の三つの空想 / A Gaijin’s Three Visions — Wiktor Sielaszuk",
    "descriptionPL": "Licencjacka praca artystyczna: autorski tryptyk audiowizualny z muzyką, wideo i trzema plakatami.",
    "descriptionEN": "Bachelor’s artistic work: an original audiovisual triptych combining music, video, and three posters.",
    "image": "assets/media/degree/gaijins-three-visions-02-fuyuu.webp",
    "imageAltPL": "Licencjacka praca artystyczna: autorski tryptyk audiowizualny z muzyką, wideo i trzema plakatami.",
    "imageAltEN": "Bachelor’s artistic work: an original audiovisual triptych combining music, video, and three posters.",
    "year": "2024"
  },
  "/projects/dissonance-perspective/": {
    "titlePL": "Dissonance Perspective — Wiktor Sielaszuk",
    "titleEN": "Dissonance Perspective — Wiktor Sielaszuk",
    "descriptionPL": "Autorska realizacja audiowizualna badająca granicę między harmonią a szumem.",
    "descriptionEN": "An original audiovisual work exploring the boundary between harmony and noise.",
    "image": "assets/media/dissonance-perspective/dissonance-perspective-02-hero-0104.webp",
    "imageAltPL": "Białe koncentryczne pierścienie na czarnym tle z realizacji Dissonance Perspective.",
    "imageAltEN": "White concentric rings on black from Dissonance Perspective.",
    "year": "2026"
  },
  "/projects/lem/": {
    "titlePL": "Lem — synteza głosu i system postaci — Wiktor Sielaszuk",
    "titleEN": "Lem — voice synthesis and character system — Wiktor Sielaszuk",
    "descriptionPL": "Modularny system postaci i rodzina bezpłatnych głosów dla OpenUTAU, UTAU i DiffSinger, rozwijane jako jedna zmienna tożsamość.",
    "descriptionEN": "A modular character system and family of free voices for OpenUTAU, UTAU, and DiffSinger, developed as one variable identity.",
    "image": "assets/media/lem/lem-three-forms-thumbnail.webp",
    "imageAltPL": "Trzy pełnopostaciowe formy Lem: Civet, Quoll i Phascogale, ustawione obok siebie.",
    "imageAltEN": "Three full-body Lem forms—Civet, Quoll, and Phascogale—arranged side by side."
  },
  "/projects/lozenge-t/": {
    "titlePL": "Lozenge T. — Wiktor Sielaszuk",
    "titleEN": "Lozenge T. — Wiktor Sielaszuk",
    "descriptionPL": "Projekt worldbuildingowy łączący fikcyjny świat, język Asaxi, autorski system pisma oraz dokumentację i narzędzia przeglądarkowe.",
    "descriptionEN": "A worldbuilding project connecting a fictional setting, the Asaxi language, an original writing system, documentation, and browser tools.",
    "image": "assets/media/lozenge-t/lozenge-t-pabaka-alphabet.webp",
    "imageAltPL": "Plansza alfabetu Pabaka z zestawem znaków pisma języka Asaxi.",
    "imageAltEN": "Pabaka alphabet board showing the character set of the Asaxi script."
  },
  "/projects/book-cover/": {
    "titlePL": "Książka, której nie napisałem — Wiktor Sielaszuk",
    "titleEN": "The Book I Did Not Write — Wiktor Sielaszuk",
    "descriptionPL": "Projekt okładki książki Mariusza Obiedzińskiego, wydanej przez Novae Res w 2025 roku.",
    "descriptionEN": "Book-cover design for Mariusz Obiedziński, published by Novae Res in 2025.",
    "image": "assets/media/book-cover/book-cover-obiedzinski-mockup.webp",
    "imageAltPL": "Makieta książki „Książka, której nie napisałem” Mariusza Obiedzińskiego i pasującej zakładki na jasnym biurku.",
    "imageAltEN": "Mockup of Mariusz Obiedziński’s book The Book I Did Not Write with a matching bookmark on a light desk.",
    "year": "2025"
  },
  "/projects/character-art/": {
    "titlePL": "Postaci - ilustracje — Wiktor Sielaszuk",
    "titleEN": "Character Art — Wiktor Sielaszuk",
    "descriptionPL": "Wybrane ilustracje postaci i plansze projektowe — od pełnych sylwetek po rozbudowane widoki referencyjne.",
    "descriptionEN": "Selected character illustrations and design sheets, from full figures to detailed reference turnarounds.",
    "image": "assets/media/character-art/character-art-01-cami-possum-witch.webp",
    "imageAltPL": "Pełnopostaciowa ilustracja Cami, oposiej wiedźmy, z laską i długim ogonem.",
    "imageAltEN": "Full-body illustration of Cami, a possum witch, with a staff and long tail."
  },
  "/projects/cover-art/": {
    "titlePL": "Okładki — Wiktor Sielaszuk",
    "titleEN": "Cover Art — Wiktor Sielaszuk",
    "descriptionPL": "Wybrane projekty okładek, w tym dwie okładki singli SVREN.",
    "descriptionEN": "Selected cover artwork, including two single covers for SVREN.",
    "image": "assets/media/cover-art/cover-art-01-untitled.webp",
    "imageAltPL": "Kwadratowa abstrakcyjna okładka w granacie i miedzianym różu z pionowym japońskim napisem.",
    "imageAltEN": "Square abstract cover in navy and copper-pink with vertical Japanese lettering."
  },
  "/projects/small-design-projects/": {
    "titlePL": "Mniejsze projekty — Wiktor Sielaszuk",
    "titleEN": "Small Design Projects — Wiktor Sielaszuk",
    "descriptionPL": "Mniejsze realizacje z zakresu ikon, identyfikacji wizualnej i grafiki użytkowej.",
    "descriptionEN": "A collection of smaller icon, visual-identity, and applied-design projects.",
    "image": "assets/media/small-design-projects/voice-model-icon.webp",
    "imageAltPL": "Geometryczny portret w błękicie i różu na niebiesko-magentowym tle, z ciemnym zakrzywionym motywem.",
    "imageAltEN": "Geometric portrait in cyan and pink on a blue-and-magenta background, with a dark curved motif."
  },
  "/projects/windows-zine/": {
    "titlePL": "WIN / DOWS — Wiktor Sielaszuk",
    "titleEN": "WIN / DOWS — Wiktor Sielaszuk",
    "descriptionPL": "Zin z 2023 roku łączący ASCII art stworzony przez ChatGPT w rozmowie z Wiktorem ze skanografią i autorskim projektem redakcyjnym.",
    "descriptionEN": "A 2023 zine combining ASCII art created by ChatGPT in conversation with Wiktor, scanography, and an original editorial design.",
    "image": "assets/media/windows-zine/windows-zine-mockup-01-hero.webp",
    "imageAltPL": "Mockup zina WIN / DOWS na szklanym stole, pokazujący okładkę i rozkładówkę.",
    "imageAltEN": "WIN / DOWS zine mockup on a glass table, showing the cover and an open spread.",
    "year": "2023"
  }
};
export const canonicalRoutes = Object.keys(routeMetadata);
export const projectRoutes = canonicalRoutes.filter(route => route.startsWith("/projects/") && route !== "/projects/");
