import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { PROJECT_ROOT, runtimeRecord, validateContent } from "./content-store.mjs";

const GENERATED_BANNER = "Generated by Portfolio Studio. Edit content/*.json, not this file.";

const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, character => ({
  "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
})[character]);
const singleLine = value => String(value ?? "").replace(/\s+/gu, " ").trim();
const escapeAttribute = value => escapeHtml(value).replace(/\r\n?|\n/g, "&#10;");

const escapeScriptJson = value => JSON.stringify(value, null, 2)
  .replace(/</g, "\\u003c")
  .replace(/\u2028/g, "\\u2028")
  .replace(/\u2029/g, "\\u2029");

function compileMedia(media) {
  if (!media || typeof media !== "object") return media;
  const output = structuredClone(media);
  if (output.kind === "group") output.items = (output.items || []).map(compileMedia);
  if (output.focalPoint && Number.isFinite(output.focalPoint.x) && Number.isFinite(output.focalPoint.y)) {
    output.objectPosition = `${Math.round(output.focalPoint.x * 10000) / 100}% ${Math.round(output.focalPoint.y * 10000) / 100}%`;
  }
  delete output.focalPoint;
  delete output.transparencyMode;
  return output;
}

function compileRuntimeRecord(record) {
  const output = runtimeRecord(record);
  for (const key of ["cover", "hero", "thumbnail"]) if (output[key]) output[key] = compileMedia(output[key]);
  if (Array.isArray(output.gallery)) output.gallery = output.gallery.map(compileMedia);
  if (output.video?.poster) output.video.poster = compileMedia(output.video.poster);
  return output;
}

function orderedContainers(bundle, { publicOnly = false } = {}) {
  return [...bundle.projects, ...bundle.collections]
    .filter(record => !publicOnly || (record.published === true && record.draft !== true))
    .sort((a, b) => Number(a.order) - Number(b.order) || a.id.localeCompare(b.id));
}

export function compileRuntimeData(bundle, { includeDrafts = false } = {}) {
  const compile = record => {
    const output = compileRuntimeRecord(record);
    if (includeDrafts) output.draft = false;
    return output;
  };
  const containers = orderedContainers(bundle, { publicOnly: !includeDrafts }).map(compile);
  const collectionIds = bundle.collections
    .filter(record => includeDrafts || (record.published === true && record.draft !== true))
    .sort((a, b) => Number(a.order) - Number(b.order) || a.id.localeCompare(b.id))
    .map(record => record.id);
  const publicWorks = bundle.works
    .filter(record => !record.detailOnly && (includeDrafts || (record.published === true && record.draft !== true)))
    .sort((a, b) => Number(a.order) - Number(b.order) || a.id.localeCompare(b.id))
    .map(compile);
  const detailMedia = bundle.works
    .filter(record => record.detailOnly && (includeDrafts || (record.published === true && record.draft !== true)))
    .sort((a, b) => Number(a.order) - Number(b.order) || a.id.localeCompare(b.id))
    .map(compile);
  return { projects: containers, collectionIds, works: publicWorks, detailMedia };
}

function previewDocument(html, kind) {
  const project = kind === "project";
  const oldAssets = project ? "../../assets/" : "../assets/";
  const newAssets = project ? "../../../assets/" : "../../assets/";
  const dataSource = project ? "../../data.js" : "../data.js";
  const oldBase = project ? 'data-base="../.."' : 'data-base=".."';
  const newBase = project ? 'data-base="../../.."' : 'data-base="../.."';
  return html
    .replaceAll(oldAssets, newAssets)
    .replace(`${newAssets}js/data.js`, dataSource)
    .replace(oldBase, newBase);
}

function routeMeta(bundle) {
  const site = bundle.site;
  const output = {
    "/": site.pages.home,
    "/portfolio/": site.pages.portfolio,
    "/projects/": site.pages.projects
  };
  for (const record of orderedContainers(bundle, { publicOnly: true })) {
    output[`/projects/${record.id}/`] = {
      ...record.seo,
      year: record.yearEN || record.yearPL || undefined
    };
  }
  return output;
}

function documentHead({ titlePL, titleEN, descriptionPL, descriptionEN, depth = 0, scripts = [] }) {
  const prefix = depth === 0 ? "./" : "../".repeat(depth);
  const inlineTitlePL = singleLine(titlePL);
  const inlineTitleEN = singleLine(titleEN);
  const inlineDescriptionPL = singleLine(descriptionPL);
  const inlineDescriptionEN = singleLine(descriptionEN);
  return `<!doctype html>
<!-- ${GENERATED_BANNER} -->
<html lang="pl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="${escapeAttribute(inlineDescriptionPL)}" data-content-pl="${escapeAttribute(inlineDescriptionPL)}" data-content-en="${escapeAttribute(inlineDescriptionEN)}">
  <title data-pl="${escapeAttribute(inlineTitlePL)}" data-en="${escapeAttribute(inlineTitleEN)}">${escapeHtml(inlineTitlePL)}</title>
  <link rel="stylesheet" href="${prefix}assets/css/site.css">
  <script type="module" src="${prefix}assets/js/media-dimensions.js"></script>
  <script type="module" src="${prefix}assets/js/site-data.js"></script>
  <script type="module" src="${prefix}assets/js/data.js"></script>
  <script type="module" src="${prefix}assets/js/typography.js"></script>
  <script type="module" src="${prefix}assets/js/core.js"></script>
${scripts.map(source => `  <script type="module" src="${prefix}${source}"></script>`).join("\n")}
</head>`;
}

function bilingualAttributes(pl, en) {
  return `data-pl="${escapeAttribute(pl)}" data-en="${escapeAttribute(en)}"`;
}

function renderHome(bundle) {
  const { site } = bundle;
  const page = site.pages.home;
  const heroLineHeight = Math.min(1.4, Math.max(0.8, Number(site.home.heroLineHeight) || 1.02));
  const heroLines = site.home.heroLines.map(line => `<span class="home-hero-heading-line" ${bilingualAttributes(line.pl, line.en)}>${escapeHtml(line.pl)}</span>`).join("");
  const disciplines = site.home.disciplines.map(item => `<div class="discipline-item"><strong ${bilingualAttributes(item.titlePL, item.titleEN)}>${escapeHtml(item.titlePL)}</strong><span ${bilingualAttributes(item.textPL, item.textEN)}>${escapeHtml(item.textPL)}</span></div>`).join("\n        ");
  const byId = new Map(orderedContainers(bundle).map(record => [record.id, record]));
  const degreeRows = site.home.degreeProjectIds.map((id, index) => {
    const record = byId.get(id);
    if (!record) return "";
    return `<a class="project-row degree-project-row" data-project-id="${escapeHtml(record.id)}" href="./projects/${escapeHtml(record.id)}/index.html"><span class="project-number">${String(index + 1).padStart(2, "0")}</span><h2 class="degree-project-title" ${bilingualAttributes(record.titlePL, record.titleEN)}>${escapeHtml(record.titlePL)}</h2><p class="degree-project-summary" ${bilingualAttributes(record.summaryPL, record.summaryEN)}>${escapeHtml(record.summaryPL)}</p><span class="project-year degree-project-year">${escapeHtml(record.yearPL)}</span><span class="project-arrow" aria-hidden="true">→</span></a>`;
  }).join("\n        ");
  return `${documentHead({ ...page, depth: 0 })}
<body data-base="." data-page="home">
  <div data-site-header></div>
  <main id="main">
    <section class="page-shell hero">
      <div class="hero-copy">
        <p class="eyebrow" ${bilingualAttributes(site.home.eyebrowPL, site.home.eyebrowEN)}>${escapeHtml(site.home.eyebrowPL)}</p>
        <h1 class="home-hero-heading" style="--home-hero-line-height:${heroLineHeight}">${heroLines}</h1>
        <p class="lead" ${bilingualAttributes(site.home.introPL, site.home.introEN)}>${escapeHtml(site.home.introPL)}</p>
        <div class="hero-actions"><a class="cta" href="./portfolio/index.html" data-pl="Zobacz całe portfolio" data-en="View the full portfolio">Zobacz całe portfolio</a><a class="text-link" href="./projects/index.html" data-pl="Poznaj projekty" data-en="Explore projects">Poznaj projekty</a></div>
      </div>
      <aside class="hero-aside" aria-label="Profil zawodowy" data-aria-pl="Profil zawodowy" data-aria-en="Professional profile"><dl><div><dt data-pl="Praktyka" data-en="Practice">Praktyka</dt><dd data-pl="projektowanie, badania, narzędzia" data-en="design, research, tools">projektowanie, badania, narzędzia</dd></div><div><dt data-pl="Obszar" data-en="Scope">Obszar</dt><dd data-pl="wizualne + językowe + techniczne" data-en="visual + linguistic + technical">wizualne + językowe + techniczne</dd></div><div><dt data-pl="Tryb" data-en="Mode">Tryb</dt><dd data-pl="eksperyment wsparty systemem" data-en="system-supported experimentation">eksperyment wsparty systemem</dd></div></dl></aside>
    </section>
    <section class="page-shell section">
      <p class="section-code">01 / <span data-pl="DYSCYPLINY" data-en="DISCIPLINES">DYSCYPLINY</span></p>
      <div class="project-overview"><h2 ${bilingualAttributes(site.home.disciplinesHeadingPL, site.home.disciplinesHeadingEN)}>${escapeHtml(site.home.disciplinesHeadingPL)}</h2><p class="lead" ${bilingualAttributes(site.home.disciplinesIntroPL, site.home.disciplinesIntroEN)}>${escapeHtml(site.home.disciplinesIntroPL)}</p></div>
      <div class="discipline-list">${disciplines}</div>
    </section>
    <section class="page-shell section degree-work-section"><p class="section-code">02 / <span data-pl="WYBRANE PRACE DYPLOMOWE" data-en="SELECTED DEGREE WORKS">WYBRANE PRACE DYPLOMOWE</span></p><div class="project-list degree-project-list">${degreeRows}</div></section>
  </main>
  <div data-site-footer></div>
</body>
</html>
`;
}

function renderPortfolio(bundle) {
  const page = bundle.site.pages.portfolio;
  return `${documentHead({ ...page, depth: 1, scripts: ["assets/js/viewer.js", "assets/js/portfolio.js"] })}
<body data-base=".." data-page="portfolio">
  <div data-site-header></div>
  <main id="main" class="page-shell">
    <header class="portfolio-head"><div><p class="section-code">P.01 / <span data-pl="ARCHIWUM PRAC" data-en="WORK ARCHIVE">ARCHIWUM PRAC</span></p><h1>Portfolio</h1></div><p class="lead" data-pl="Wybrane prace z filtrowaniem według projektu, roku, medium i typu." data-en="Selected work, filterable by project, year, medium, and type.">Wybrane prace z filtrowaniem według projektu, roku, medium i typu.</p></header>
    <nav class="mode-tabs" aria-label="Widok portfolio" data-aria-pl="Widok portfolio" data-aria-en="Portfolio view"><a class="mode-tab" href="./index.html" aria-current="page" data-pl="Wszystkie prace" data-en="All work">Wszystkie prace</a><a class="mode-tab" href="../projects/index.html" data-projects-mode-link data-pl="Projekty" data-en="Projects">Projekty</a></nav>
    <section class="display-toolbar" aria-label="Ustawienia widoku" data-aria-pl="Ustawienia widoku" data-aria-en="Display settings"><div class="display-controls" data-display-controls></div></section>
    <section class="filter-zone" aria-labelledby="filter-heading"><h2 id="filter-heading" class="filter-label" data-pl="Filtry galerii" data-en="Gallery filters">Filtry galerii</h2><div class="filter-bar" data-filters></div><div class="selection-summary" data-selection-summary aria-live="polite"></div></section>
    <div class="results-meta"><span class="result-count" data-result-count tabindex="-1" aria-live="polite"></span><span class="muted" data-pl="W obrębie kategorii działa LUB; między kategoriami działa ORAZ." data-en="Within a facet, filters use OR; across facets, they use AND.">W obrębie kategorii działa LUB; między kategoriami działa ORAZ.</span></div>
    <section class="gallery-grid" data-gallery aria-label="Galeria prac" data-aria-pl="Galeria prac" data-aria-en="Work gallery"></section><div class="pagination" data-pagination></div>
    <section class="zero-state" data-zero-state><p class="section-code">00 / <span data-pl="BRAK WYNIKÓW" data-en="NO RESULTS">BRAK WYNIKÓW</span></p><h2 data-pl="Brak prac dla tej kombinacji." data-en="No work matches this combination.">Brak prac dla tej kombinacji.</h2><p class="lead" data-pl="Usuń jeden lub więcej filtrów albo wyczyść zestaw i zacznij od nowa." data-en="Remove one or more filters, or clear the set and start again.">Usuń jeden lub więcej filtrów albo wyczyść zestaw i zacznij od nowa.</p><p><button class="cta secondary" type="button" data-zero-clear data-pl="Wyczyść filtry" data-en="Clear filters">Wyczyść filtry</button></p></section>
  </main><div data-site-footer></div>
</body></html>
`;
}

function renderProjects(bundle) {
  const page = bundle.site.pages.projects;
  return `${documentHead({ ...page, depth: 1, scripts: ["assets/js/viewer.js", "assets/js/projects.js"] })}
<body data-base=".." data-page="projects"><div data-site-header></div><main id="main" class="page-shell">
  <header class="portfolio-head"><div><p class="section-code">P.02 / <span data-pl="PROJEKTY KURATORSKIE" data-en="CURATED PROJECTS">PROJEKTY KURATORSKIE</span></p><h1 data-pl="Projekty" data-en="Projects">Projekty</h1></div><p class="lead" data-pl="Wybrane projekty z opisami założeń, procesu, roli i użytych mediów." data-en="Selected projects with context on concept, process, role, and media.">Wybrane projekty z opisami założeń, procesu, roli i użytych mediów.</p></header>
  <nav class="mode-tabs" aria-label="Widok portfolio" data-aria-pl="Widok portfolio" data-aria-en="Portfolio view"><a class="mode-tab" href="../portfolio/index.html" data-works-mode-link data-pl="Wszystkie prace" data-en="All work">Wszystkie prace</a><a class="mode-tab" href="./index.html" aria-current="page" data-pl="Projekty" data-en="Projects">Projekty</a></nav>
  <section class="section"><p class="section-code">01–11 / <span data-pl="PEŁNY INDEKS" data-en="COMPLETE INDEX">PEŁNY INDEKS</span></p><div class="display-toolbar"><div class="display-controls" data-display-controls></div></div><div class="project-list" data-project-list></div><div class="pagination" data-pagination></div></section>
</main><div data-site-footer></div></body></html>
`;
}

function renderBrandMark(record) {
  if (!record.brandMark) return "";
  const mark = record.brandMark;
  return `<div class="lem-logo-lockup" role="img" aria-label="${escapeHtml(mark.altPL)}" data-aria-pl="${escapeHtml(mark.altPL)}" data-aria-en="${escapeHtml(mark.altEN)}"><img src="../../${escapeHtml(mark.src)}" width="1622" height="567" alt="" aria-hidden="true"></div>`;
}

function renderProject(record) {
  const seo = record.seo;
  const legacyHeroLineHeight = Number(record.heroLineHeight) || 1.12;
  const heroLineHeightPL = Math.min(1.4, Math.max(0.8, Number(record.heroLineHeightPL) || legacyHeroLineHeight));
  const heroLineHeightEN = Math.min(1.4, Math.max(0.8, Number(record.heroLineHeightEN) || legacyHeroLineHeight));
  const hasScript = Array.isArray(record.scriptRows) && record.scriptRows.length > 0;
  const sequenceNumber = hasScript ? "03" : "02";
  const processNumber = hasScript ? "04" : "03";
  const relatedNumber = hasScript ? "05" : "04";
  const cover = record.id === "lozenge-t" ? "" : `<div class="project-cover" data-project-cover></div>`;
  const projectLinks = record.externalLinks?.length ? `<nav class="project-links" data-project-links aria-label="${escapeHtml(record.titlePL)}" hidden></nav>` : "";
  const script = hasScript ? `<section class="page-shell section pabaka-showcase" data-project-script></section>` : "";
  return `${documentHead({ ...seo, depth: 2, scripts: ["assets/js/viewer.js", "assets/js/project-detail.js"] })}
<body data-base="../.." data-page="projects" data-project="${escapeHtml(record.id)}"><div data-site-header></div><main id="main"><article>
  <header class="page-shell project-hero" style="--project-hero-line-height-pl:${heroLineHeightPL};--project-hero-line-height-en:${heroLineHeightEN}"><p class="section-code">${escapeHtml(record.pageCode || "P.03")} / <span ${bilingualAttributes(record.pageLabelPL || "PROJEKT KURATORSKI", record.pageLabelEN || "CURATED PROJECT")}>${escapeHtml(record.pageLabelPL || "PROJEKT KURATORSKI")}</span></p><div class="project-hero-grid"><div><h1 data-project-title></h1><p class="lead" data-project-summary></p></div><dl class="project-meta"><div><dt data-pl="Rok" data-en="Year">Rok</dt><dd data-project-year></dd></div><div><dt data-pl="Dyscypliny" data-en="Disciplines">Dyscypliny</dt><dd data-project-disciplines></dd></div><div><dt>Format</dt><dd data-project-format></dd></div></dl></div>${renderBrandMark(record)}${cover}</header>
  <section class="page-shell section project-overview"><div><p class="section-code">01 / <span data-pl="ZAŁOŻENIA" data-en="CONCEPT">ZAŁOŻENIA</span></p><h2 data-pl="Założenia, proces i zakres." data-en="Concept, process, and scope.">Założenia, proces i zakres.</h2></div><div><p class="lead" data-project-overview></p>${projectLinks}<dl class="project-meta"><div><dt data-pl="Rola / zakres" data-en="Role / scope">Rola / zakres</dt><dd data-project-role></dd></div><div><dt data-pl="Media" data-en="Media">Media</dt><dd data-project-media></dd></div></dl></div></section>
  ${script}
  <section class="page-shell section"><p class="section-code">${sequenceNumber} / <span data-pl="SEKWENCJA PRAC" data-en="WORK SEQUENCE">SEKWENCJA PRAC</span></p><div class="curated-sequence" data-curated-sequence></div></section>
  <section class="page-shell section" data-process-section><p class="section-code">${processNumber} / <span data-pl="PROCES I KREDYTY" data-en="PROCESS AND CREDITS">PROCES I KREDYTY</span></p><div class="project-overview"><h2 data-project-process-heading></h2><div class="detail-copy"><p class="lead" data-project-process></p><p data-project-credits></p></div></div></section>
  <section class="page-shell section related-projects-section" aria-labelledby="related-heading-${escapeHtml(record.id)}"><h2 class="section-code related-section-heading" id="related-heading-${escapeHtml(record.id)}">${relatedNumber} / <span data-pl="POWIĄZANE PROJEKTY" data-en="RELATED PROJECTS">POWIĄZANE PROJEKTY</span></h2><div class="related-grid" data-related-projects></div></section>
</article></main><div data-site-footer></div></body></html>
`;
}

function buildSeoModule(bundle) {
  const meta = Object.fromEntries(Object.entries(routeMeta(bundle)).map(([route, item]) => [route, {
    ...item,
    titlePL: singleLine(item.titlePL),
    titleEN: singleLine(item.titleEN),
    descriptionPL: singleLine(item.descriptionPL),
    descriptionEN: singleLine(item.descriptionEN)
  }]));
  return `// ${GENERATED_BANNER}\nexport const ORIGIN = ${JSON.stringify(bundle.site.origin)};\nexport type RouteMeta = { titlePL: string; titleEN: string; descriptionPL: string; descriptionEN: string; image?: string; imageAltPL?: string; imageAltEN?: string; year?: string; };\nexport const routeMetadata: Record<string, RouteMeta> = ${escapeScriptJson(meta)};\nexport const canonicalRoutes = Object.keys(routeMetadata);\nexport const projectRoutes = canonicalRoutes.filter(route => route.startsWith(\"/projects/\") && route !== \"/projects/\");\n`;
}

function buildManifest(bundle) {
  const containers = orderedContainers(bundle, { publicOnly: true });
  return {
    schemaVersion: 1,
    generatedAt: "deterministic",
    routes: [
      { name: "home", route: "/", file: "index.html" },
      { name: "portfolio", route: "/portfolio/", file: "portfolio/index.html" },
      { name: "projects", route: "/projects/", file: "projects/index.html" },
      ...containers.map(record => ({ name: record.id, route: `/projects/${record.id}/`, file: `projects/${record.id}/index.html`, recordType: record.recordType }))
    ]
  };
}

function buildSitemap(bundle) {
  const routes = buildManifest(bundle).routes;
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${routes.map(({ route }) => `  <url><loc>${escapeHtml(bundle.site.origin)}${route}</loc></url>`).join("\n")}\n</urlset>\n`;
}

async function existing(file) {
  try { return await readFile(file, "utf8"); } catch (error) { if (error.code === "ENOENT") return null; throw error; }
}

async function atomicWrite(file, content) {
  await mkdir(path.dirname(file), { recursive: true });
  if (await existing(file) === content) return false;
  const temp = `${file}.${process.pid}.tmp`;
  await writeFile(temp, content, "utf8");
  await rename(temp, file);
  return true;
}

export async function generateSite(bundle, { root = PROJECT_ROOT, check = false, preview = false } = {}) {
  const validation = await validateContent(bundle, { root, checkFiles: true, publish: false });
  if (!validation.valid) {
    const error = new Error(`Content validation failed with ${validation.errors.length} error(s).`);
    error.validation = validation;
    throw error;
  }
  const runtime = compileRuntimeData(bundle);
  const manifest = buildManifest(bundle);
  const outputs = new Map([
    ["assets/js/data.js", `// ${GENERATED_BANNER}\nwindow.PORTFOLIO_DATA = ${escapeScriptJson(runtime)};\n`],
    ["assets/js/site-data.js", `// ${GENERATED_BANNER}\nwindow.PORTFOLIO_SITE = ${escapeScriptJson(bundle.site)};\n`],
    ["seo-metadata.ts", buildSeoModule(bundle)],
    ["generated/site-manifest.json", `${JSON.stringify(manifest, null, 2)}\n`],
    ["public/sitemap.xml", buildSitemap(bundle)],
    ["index.html", renderHome(bundle)],
    ["portfolio/index.html", renderPortfolio(bundle)],
    ["projects/index.html", renderProjects(bundle)]
  ]);
  for (const record of orderedContainers(bundle, { publicOnly: true })) outputs.set(`projects/${record.id}/index.html`, renderProject(record));
  if (preview && !check) {
    const previewRuntime = compileRuntimeData(bundle, { includeDrafts: true });
    outputs.set("studio-preview/data.js", `// Local draft preview; never publish.\nwindow.PORTFOLIO_DATA = ${escapeScriptJson(previewRuntime)};\n`);
    outputs.set("studio-preview/portfolio/index.html", previewDocument(renderPortfolio(bundle), "index"));
    outputs.set("studio-preview/projects/index.html", previewDocument(renderProjects(bundle), "index"));
    for (const record of orderedContainers(bundle)) outputs.set(`studio-preview/projects/${record.id}/index.html`, previewDocument(renderProject(record), "project"));
  }

  const drift = [];
  let changed = 0;
  for (const [relative, content] of outputs) {
    const file = path.resolve(root, relative);
    const previous = await existing(file);
    if (previous !== content) drift.push(relative);
    if (!check && previous !== content && await atomicWrite(file, content)) changed += 1;
  }
  if (check && drift.length) {
    const error = new Error(`Generated outputs are stale: ${drift.join(", ")}`);
    error.drift = drift;
    throw error;
  }
  return { changed, drift, manifest, validation };
}

export async function removeOwnedRoute(file, { root = PROJECT_ROOT } = {}) {
  const absolute = path.resolve(root, file);
  if (!absolute.startsWith(`${path.resolve(root)}${path.sep}`)) throw new Error("Owned route escaped the repository.");
  const source = await existing(absolute);
  if (source && source.includes(GENERATED_BANNER)) await rm(absolute, { force: true });
}
